### ISSUE TITLE
[1.0] Support Schema.org JobPosting MicroFormat

### ISSUE THREAD

**Issue by stevenmaguire** [JobBrander/jobs-common#1]
Should we support this?

http://schema.org/JobPosting

**Comment by karllhughes** [comment]
I would be fine with it. The attributes I picked are somewhat arbitrary. 

I've never used a schema standard like this, although I have seen them before. Can we add to it, or is it strictly composed of the attributes listed?

**Comment by karllhughes** [comment]
Based on our discussion last weekend, I propose we adopt the following Schema.org standards for JobPosting:
- Extend JobPosting schema JobPosting (as we are doing in the `schema-support` branch) so that all schema attributes can be set by the provider if desired
- For our "setMinimumSalary" method, if the salary is a number, set the "baseSalary" attribute to equal the same thing
- Support the following methods for setting the job location (as done in setState() and setCity() methods currently in branch):
  - setState => Place->PostalAddress->addressRegion
  - setCity => Place->PostalAddress->addressLocality
  - setCountry => Place->PostalAddress->addressCountry
  - setPostalCode => Place->PostalAddress->postalCode
  - setAddress => Place->PostalAddress->streetAddress
  - setTelephone => Place->telephone
- Support for the following methods for setting company data:
  - setCompanyName
  - setCompanyDescription
  - setCompanyLogo
  - setCompanyEmail
  - setCompanyUrl

The reason I don't want to get into company location is that I think it's outside the scope of this project. We are concerned with Jobs, Locations of those Jobs, and Companies that post those Jobs. Once we get beyond one level of separation, I think we should cut it off.

I'm going to build those methods and commit to the branch, then let you review it before moving forward @stevenmaguire.

**Comment by karllhughes** [comment]
Added as of 5/8/15 in 0.3.2 release
