### ISSUE TITLE
Clean up Job Object

### ISSUE THREAD

**Issue by karllhughes** [JobBrander/jobs-common#15]
The Job Object is getting quite big and the methods aren't really organized. 

Thoughts on how we might help fix this:

- Alphebetize and/or organize methods by function

- Move the private methods at the end to another trait or parent class

- Move location related attributes to their own trait (same with company related methods)

What do you think? It's not that 800 lines is too long, but I think we should do something to encourage modularity if we decide there's a new group of attributes we want to add later. @stevenmaguire would love your input.

**Comment by karllhughes** [comment]
Moved the company and location traits into their own files in this branch just to see how it might work: https://github.com/JobBrander/jobs-common/tree/splitting_job_class

I like the idea of splitting it up, but I'm not sure if having a bunch of traits is very good practice.

**Comment by stevenmaguire** [comment]
Alphabetizing and grouping the public methods is a good idea. 

Alphabetizing and grouping the private methods is a good idea. 

I don't think you can safely move those items into separate traits because they are 100% dependent on the parent class. (eg: `$location = parent::getJobLocation();`). I don't think this needs to be addressed right now.

There are plenty of examples of well maintained code with classes whose line count is in the thousands; one particular example that stands out is the Model in Laravel (https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Eloquent/Model.php).

I think we are ok!

**Comment by karllhughes** [comment]
Great. I'll do the alphabetizing then.

I will definitely defer to your knowledge on using traits. Thanks for your input!

**Comment by stevenmaguire** [comment]
There's also this list of issues https://scrutinizer-ci.com/g/JobBrander/jobs-common/inspections/2ac8154d-4ff2-479a-a6ed-732a4dd98b9a/issues/?status=all

**Comment by stevenmaguire** [comment]
I cleaned up all the issues scrutinizer was wining about. 

https://scrutinizer-ci.com/g/JobBrander/jobs-common/inspections/f22a3c3d-39f5-4e4d-b638-099aa778cf94

The code quality bit is still less than desired but that is related to the large classes.

**Comment by karllhughes** [comment]
Alphebetizing/reorganizing is complete.
