### ISSUE TITLE
[1.0] Add support for JSON-LD as per the spec

### ISSUE THREAD

**Issue by stevenmaguire** [JobBrander/jobs-common#19]
I added some code to provide some help for folks who are interested in serializing the object as JSON LD, as indicated in the spec: http://schema.org/JobPosting

The tests still cover the code 100%, but there is still some room to explicitly test that the resulting object matches the specific data. 

I also envisioned providing a way to force the level of strictness within the serialization. This could be used to indicate if the resulting object was a clean json serialization or included LD, or perhaps it excluded the non-explicit Schema.org properties.

I am curious on your thoughts, @karllhughes.

Feel free to contribute directly to the branch `microformat-json`

**Comment by karllhughes** [comment]
Ok cool, I'll look over this in the next few days and let you know what I think.

**Comment by karllhughes** [comment]
I added some more tests to the microformatting data, so that should take care of your concern over data matching.

I think that offering different output formats or converting data to formats is a great feature that makes the library much more flexible. I don't have a strong opinion about whether to strictly enforce serialization since it isn't really relevant to my first use case, but I think that the ability to set flags in the serialize() function might make sense.

**Comment by stevenmaguire** [comment]
What kinds of flags do you think will be valuable? Binary like JSON-LD with only the core schema properties populated or plain old JSON with no contextual keys and all of the properties?

**Comment by karllhughes** [comment]
Flag ideas:
- `standard` Ordinary json with all properties
- `standard-ld` Ordinary json with linkedin data
- `core-schema` Only the core schema properties in json-ld

I'm totally guessing here since in my current implementation I'd probably just need "standard" but this gives us a starting point.
