### ISSUE TITLE
Make Companies, Locations, Industries singular on Job object

### ISSUE THREAD

**Issue by stevenmaguire** [JobBrander/jobs-common#4]
@karllhughes What is the use case for the following items needing to be lists/arrays in the `Job` object?

- companies
- locations
- industries
- codes

I've got some thoughts on how to handle these items. I would like to validate them against the use cases you began with.

**Comment by karllhughes** [comment]
Companies:
All providers I've seen only provide one. I just made it plural in case future vendors provide multiple companies for a job. Seems unlikely, so we can probably just make this singular

Locations:
The govt api gives 1 or more locations for each job listing, so I think we should keep this one as an array.

Industries:
Jobs2Careers offers a single industry for each job. I made this plural in case other providers offered more later.

Codes:
This is a place for special codes provided in each job listing. Some providers offer javascript snippets or special ids for their jobs, so it's kind of a catch-all.

**Comment by stevenmaguire** [comment]
Companies: Let's make singular.
Industries: Let's make singular.

Good with those two?

Locations: In this instance is it one job that reports to multiple locations, or multiple jobs with the same classification/details that are available in multiple locations; each only responsible to report to one location?

Codes: is it your observation that codes would contain strings of text that could be executable javascript or miscellaneous strings of identifying data? Is it possible to identify these unique purposes and build for them with intent? One of the benefits of a common base library is that the purpose of each of the methods on the common returned object is decoupled from the vendor supplying the information. If the vendor changes the purpose of the resulting object should not.

**Comment by karllhughes** [comment]
Good on the first two.

For locations: I think it's multiple jobs, but the government's wonky system puts them in the same id. For my purposes, I've just been truncating the locations and only taking the first one listed anyway. Making them into multiple jobs might make more sense.

Codes are very provider dependent. It's probably the least standardized form of data here. Some use names of JS functions, some use unique id's, and some are job codes with unspecified use to the casual observer (probably for internal tools). Since the codes are required to truly implement some of the API's we need to keep them, but they aren't all done the same way and I feel like future providers might add new methods, so keeping codes general is sort of my fall back place for non-standard but necessary data.

**Comment by stevenmaguire** [comment]
Locations: Could we make the property singular and coerce vendor implementations to generate a CSV value of all the locations?

Codes: Let's move this puppy to a dedicated issue and continue the conversation. There are a lot of good changes that have clarity here now. I'll do that.

**Comment by karllhughes** [comment]
A CSV is fine. I'll need to make a to do list item in the govt provider to
fix that.

Karl L. Hughes
(901) 827-9637
Google+ <https://plus.google.com/101080316492181821858> | LinkedIn
<http://www.linkedin.com/in/karllhughes> | Twitter
<http://twitter.com/karllhughes> | Web <http://karllhughes.com>
